set echo on
set time on
set timing on

spool 25-CREATE_PEP_ROLE_TABLE_DML.out

show user;


select to_char (sysdate, 'Dy DD-MON-YYYY @ HH24:MI:SS')
                as " Job Began at:" from dual;

host hostname;


--- ******** SCRIPT - BEGIN SQL *********************


set define off;

  
REM INSERTING into VENDORPORTAL.PEP_ROLE
SET DEFINE OFF;
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('ART DIRECTOR','ACTIVE','BELK_USER',null,'ADMIN',to_timestamp('12-AUG-15 04.20.27.780000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('DCA','ACTIVE','BELK_USER',null,'ADMIN',to_timestamp('12-AUG-15 04.14.23.776000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('DCAA','ACTIVE','BELK_USER',null,'ADMIN',to_timestamp('12-AUG-15 04.17.12.272000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('SAMPLE COORDINATOR','ACTIVE','BELK_USER',null,'ADMIN',to_timestamp('12-AUG-15 04.21.07.687000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('VENDOR','ACTIVE','EXTERNAL_USER',null,'ADMIN',to_timestamp('12-AUG-15 04.11.34.713000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into VENDORPORTAL.PEP_ROLE (PEP_ROLE_ID,ROLE_STATUS,USER_TYPE,ACCESS_TYPE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) values ('VIEW ONLY','ACTIVE','BELK_USER',null,'ADMIN',to_timestamp('05-AUG-15 04.23.37.483000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null);

 
COMMIT;

--- ******** DATABASE CONTROLS - AFTER   SCRIPT ******

--- ****************************************************
select to_char (sysdate, 'Dy DD-MON-YYYY @ HH24:MI:SS')
                as " Job Ended at: " from dual;

exit;