set echo on
set time on
set timing on

spool 25-CREATE_PEP_TABLES_DDL.out

show user;


select to_char (sysdate, 'Dy DD-MON-YYYY @ HH24:MI:SS')
                as " Job Began at:" from dual;

host hostname;


--- ******** SCRIPT - BEGIN SQL *********************


set define off;


  CREATE TABLE "VENDORPORTAL"."PEP_ROLE" 
   (	"PEP_ROLE_ID" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"ROLE_STATUS" VARCHAR2(40 BYTE), 
	"USER_TYPE" VARCHAR2(40 BYTE), 
	"ACCESS_TYPE" VARCHAR2(40 BYTE), 
	"CREATED_BY" VARCHAR2(60 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(40 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PEP_ROLE_PK" PRIMARY KEY ("PEP_ROLE_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" 
 PCTTHRESHOLD 50;
 
 
  CREATE TABLE "VENDORPORTAL"."EXTERNAL_USER" 
   (	"SUPPLIER_ID" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"SUPPLIER_EMAIL" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"DEPT_FILTER_ID" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(80 BYTE), 
	"LAST_NAME" VARCHAR2(80 BYTE), 
	"PRIMARY_EMAIL" VARCHAR2(80 BYTE), 
	"SUPPLIER_PWD" VARCHAR2(80 BYTE), 
	"PEP_ROLE_ID" VARCHAR2(80 BYTE), 
	"PWD_STATUS" VARCHAR2(60 BYTE), 
	"FAILED_LOGIN_ATTEMPTS" NUMBER, 
	"LAST_LOGIN_DATE_TIME" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(80 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "EXTERNAL_USER_PK" PRIMARY KEY ("SUPPLIER_ID", "SUPPLIER_EMAIL", "DEPT_FILTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VPORT_DATA"  ENABLE, 
	 CONSTRAINT "EXTERNAL_USER_FK1" FOREIGN KEY ("PEP_ROLE_ID")
	  REFERENCES "VENDORPORTAL"."PEP_ROLE" ("PEP_ROLE_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VPORT_DATA" ;


  CREATE TABLE "VENDORPORTAL"."BELK_USER" 
   (	"BELK_ID" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"BELK_EMAIL" VARCHAR2(80 BYTE), 
	"LAST_LOGIN_DATE_TIME" TIMESTAMP (6), 
	"PEP_ROLE_ID" VARCHAR2(80 BYTE), 
	"CREATED_BY" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(80 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 PRIMARY KEY ("BELK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA"  ENABLE, 
	 CONSTRAINT "BELK_USER_FK1" FOREIGN KEY ("PEP_ROLE_ID")
	  REFERENCES "VENDORPORTAL"."PEP_ROLE" ("PEP_ROLE_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
  
  
  
  CREATE TABLE "VENDORPORTAL"."PEP_DEPARTMENT" 
   (	"DEPT_ID" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"DEPT_NAME" VARCHAR2(80 BYTE), 
	"PEP_USER_ID" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(80 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PEP_DEPARTMENT_PK" PRIMARY KEY ("DEPT_ID", "PEP_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VPORT_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VPORT_DATA" ;
  
  
   CREATE TABLE "VENDORPORTAL"."CONFIG" 
   (	"CONFIG_ID" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"PARAM" VARCHAR2(80 BYTE), 
	"VALUE" VARCHAR2(80 BYTE), 
	"CREATED_BY" VARCHAR2(80 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(80 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VPORT_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VPORT_DATA" ;


  CREATE TABLE "VENDORPORTAL"."PET_ATTRIBUTE" 
   (	"ATTR_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CATEGORY_ID" VARCHAR2(50 BYTE), 
	"ATTRIBUTE_NAME" VARCHAR2(60 BYTE), 
	"DISPLAY_NAME" VARCHAR2(60 BYTE), 
	"DISPLAYABLE" VARCHAR2(10 BYTE), 
	"EDITABLE" VARCHAR2(10 BYTE), 
	"MANDATORY" VARCHAR2(10 BYTE), 
	"HTML_DISPLAY_CODE" VARCHAR2(20 BYTE), 
	"HTML_DISPLAY_DESC" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"CREATED_DATE" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" TIMESTAMP (6), 
	 CONSTRAINT "PET_ATTRIBUTE_PK" PRIMARY KEY ("ATTR_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" 
 PCTTHRESHOLD 50;



 
COMMIT;

--- ******** DATABASE CONTROLS - AFTER   SCRIPT ******

--- ****************************************************
select to_char (sysdate, 'Dy DD-MON-YYYY @ HH24:MI:SS')
                as " Job Ended at: " from dual;

exit;