ALTER TABLE VENDORPORTAL.ADSE_PET_CATALOG
	ADD EXIST_IN_GROUP VARCHAR2(1) DEFAULT 'N';

DROP TABLE VENDORPORTAL.ADSE_GROUP_CATALOG;

--------------------------------------------------------
--  DDL for Table LOG_ERROR_DATA
--------------------------------------------------------

  CREATE TABLE "VENDORPORTAL"."LOG_ERROR_DATA" 
   (	"KEY_VALUE" VARCHAR2(20 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;

  
ALTER TABLE VENDORPORTAL.ADSE_ITEM_CATALOG 
ADD  ( 
PETEXISTS 		CHAR(1) DEFAULT 'N',       
PRODUCT_NAME    VARCHAR2(1000), 
COLOR_CODE      VARCHAR2(20),
COLOR_NAME     	VARCHAR2(100),  
SIZE_NAME       VARCHAR2(100), 
SIZE_CODE      	VARCHAR2(20) );


