--------------------------------------------------------
--  File created - Thursday-June-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADSE_GROUP_CATALOG
--------------------------------------------------------

  CREATE TABLE "VENDORPORTAL"."ADSE_GROUP_CATALOG" 
   (	"ID" NUMBER(11,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 107 CACHE 20 NOORDER  NOCYCLE , 
	"MDMID" VARCHAR2(50 BYTE), 
	"MDMKEY" NUMBER(11,0) DEFAULT -1, 
	"ENTRY_TYPE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"GROUP_NAME" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"DELETED_FLAG" VARCHAR2(5 BYTE) DEFAULT 'false', 
	"CREATED_DTM" TIMESTAMP (6) DEFAULT current_timestamp, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"LST_UPT_DTM" TIMESTAMP (6) DEFAULT NULL, 
	"LST_UPT_BY" VARCHAR2(50 BYTE), 
	"GROUP_OVERALL_STATUS_CODE" VARCHAR2(20 BYTE), 
	"GROUP_CONTENT_STATUS_CODE" VARCHAR2(20 BYTE), 
	"GROUP_IMAGE_STATUS_CODE" VARCHAR2(20 BYTE), 
	"PRE_CUT_OVER_FLAG" VARCHAR2(20 BYTE), 
	"COMPLETION_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PET_SOURCE" VARCHAR2(20 BYTE), 
	"DEF_DEPT_ID" VARCHAR2(64 BYTE), 
	"DEF_PRIMARYSUPPLIERVPN" VARCHAR2(64 BYTE), 
	"DEF_PRIMARY_SUPPLIER_ID" VARCHAR2(64 BYTE), 
	"EXIST_IN_GROUP" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PET_DISPLAY_FLAG" VARCHAR2(1 BYTE) DEFAULT 'P'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "VPORT_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;

   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."COMPLETION_DATE" IS 'Shredded Column at PEP';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."START_DATE" IS 'Shredded Column at PEP';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."END_DATE" IS 'Shredded Column at PEP';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."PET_SOURCE" IS 'Shredded Column at PEP';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."DEF_DEPT_ID" IS 'Updated through Trigger';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."DEF_PRIMARYSUPPLIERVPN" IS 'Updated through Trigger';
   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CATALOG"."DEF_PRIMARY_SUPPLIER_ID" IS 'Updated through Trigger';
