--------------------------------------------------------
--  File created - Thursday-June-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADSE_GROUP_CHILD_MAPPING
--------------------------------------------------------

  CREATE TABLE "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" 
   (	"MDMID" VARCHAR2(50 BYTE), 
	"COMPONENT_GROUPING_ID" VARCHAR2(100 BYTE), 
	"COMPONENT_STYLE_ID" VARCHAR2(100 BYTE), 
	"COMPONENT_STYLECOLOR_ID" VARCHAR2(100 BYTE), 
	"COMPONENT_SKU_ID" VARCHAR2(100 BYTE), 
	"COMPONENT_TYPE" VARCHAR2(100 BYTE), 
	"DISPLAY_SEQUENCE" VARCHAR2(5 BYTE), 
	"COMPONENT_DEFAULT" VARCHAR2(5 BYTE), 
	"ID" NUMBER(11,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"COMPONENT_MDMID" VARCHAR2(100 BYTE), 
	"PEP_COMPONENT_TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;

   COMMENT ON COLUMN "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING"."COMPONENT_MDMID" IS 'PEP Column to show the component irrespective of the COMPONENT_TYPE';
