
  CREATE INDEX "VENDORPORTAL"."PERF_IDX1" ON "VENDORPORTAL"."ADSE_ITEM_CATALOG" ("ENTRY_TYPE", "DELETED_FLAG", "PRIMARYSUPPLIERVPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;


  CREATE INDEX "VENDORPORTAL"."PERF_IDX4" ON "VENDORPORTAL"."ADSE_PET_CATALOG" ("PET_STATE", "WLIST_DISPLAY_FLAG", "ENTRY_TYPE", "PET_STYLE_STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;

  --------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_STATUS_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_STATUS_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("GROUP_OVERALL_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_PETSRC_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_PETSRC_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("PET_SOURCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_MDMID_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDORPORTAL"."ADSE_GRPCTG_MDMID_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("MDMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_GRPNAME_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_GRPNAME_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("GROUP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_CRTDTM_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_CRTDTM_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("CREATED_DTM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_ID_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDORPORTAL"."ADSE_GRPCTG_ID_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_CONTENT_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_CONTENT_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("GROUP_CONTENT_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCTG_IMAGE_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCTG_IMAGE_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CATALOG" ("GROUP_IMAGE_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;

  --------------------------------------------------------
--  DDL for Index ADSE_GROUP_CHILD_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING_PK" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCHILD_COMPDFLT_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCHILD_COMPDFLT_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("COMPONENT_DEFAULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCHILD_COMPTYPE_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCHILD_COMPTYPE_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("COMPONENT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index ADSE_GRPCHILD_MDMID_IDX
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."ADSE_GRPCHILD_MDMID_IDX" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("MDMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index PERF_IDX5
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."PERF_IDX5" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("COMPONENT_STYLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index PERF_IDX2
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."PERF_IDX2" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("COMPONENT_STYLECOLOR_ID", "COMPONENT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  DDL for Index PERF_IDX3
--------------------------------------------------------

  CREATE INDEX "VENDORPORTAL"."PERF_IDX3" ON "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ("COMPONENT_SKU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;
--------------------------------------------------------
--  Constraints for Table ADSE_GROUP_CHILD_MAPPING
--------------------------------------------------------

  
  ALTER TABLE "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" ADD CONSTRAINT "ADSE_GROUP_CHILD_MAPPING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA"  ENABLE;
  ALTER TABLE "VENDORPORTAL"."ADSE_GROUP_CHILD_MAPPING" MODIFY ("MDMID" NOT NULL ENABLE);


  CREATE INDEX "VENDORPORTAL"."PERF_IDX1" ON "VENDORPORTAL"."ADSE_ITEM_CATALOG" ("ENTRY_TYPE", "DELETED_FLAG", "PRIMARYSUPPLIERVPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;


  CREATE INDEX "VENDORPORTAL"."PERF_IDX4" ON "VENDORPORTAL"."ADSE_PET_CATALOG" ("PET_STATE", "WLIST_DISPLAY_FLAG", "ENTRY_TYPE", "PET_STYLE_STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VPORT_DATA" ;



