--------------------------------------------------------
--  DDL for Trigger T_ADSE_GRPCHLD_GRP_DFLT_AIUR
--------------------------------------------------------

  CREATE OR REPLACE  TRIGGER "VENDORPORTAL"."T_ADSE_GRPCHLD_GRP_DFLT_AIUR" 
  FOR INSERT OR UPDATE OF COMPONENT_DEFAULT ON VENDORPORTAL.ADSE_GROUP_CHILD_MAPPING
    COMPOUND TRIGGER 
Updatesqlquery          VARCHAR2(600);
L_COMPONENT_STYLE_ID VENDORPORTAL.ADSE_GROUP_CHILD_MAPPING.COMPONENT_STYLE_ID%type;
L_COMPONENT_DEFAULT VENDORPORTAL.ADSE_GROUP_CHILD_MAPPING.COMPONENT_DEFAULT%type;
L_MDMID VENDORPORTAL.ADSE_GROUP_CATALOG.MDMID%type;
L_COMPONENT_TYPE VENDORPORTAL.ADSE_GROUP_CHILD_MAPPING.PEP_COMPONENT_TYPE%type;
L_COMPONENT_GROUPING_ID VENDORPORTAL.ADSE_GROUP_CHILD_MAPPING.COMPONENT_GROUPING_ID%type;
L_COMPMDMID             VARCHAR2(100);
L_sql_code              INT :=0;
L_sql_err               VARCHAR2(2000) := NULL;
/*
This Trigger will update the ADSE_GROUP_CATALOG Default Values based on the Default selection in ADSE_GROUP_CATALOG
ON INSERT or UPDATE of ADSE_GROUP_CATALOG.COMPONENT_DEFAULT  to true will execute the update statement in ADSE_GROUP_CATALOG
*/

BEFORE EACH ROW
IS BEGIN
IF INSERTING THEN
  IF (:NEW.COMPONENT_TYPE IN ('Style','StyleColor','SKU')) THEN
    :NEW.PEP_COMPONENT_TYPE := :NEW.COMPONENT_TYPE;
  ELSE
    :NEW.PEP_COMPONENT_TYPE :='Group';
  END IF;
END IF;
EXCEPTION
  WHEN OTHERS THEN
    L_sql_code := SQLCODE;
    L_sql_err  := SUBSTR(SQLERRM,1,200);
    DBMS_OUTPUT.PUT_LINE ('Trigger T_ADSE_GRPCHLD_TO_GRP_AIUR BEFORE EACH ROW  Error = '||L_sql_code || L_sql_err);
	raise_application_error(-20000, 'Fatal error from trigger T_ADSE_GRPCHLD_TO_GRP_AIUR BEFORE EACH ROW   '||L_sql_code || L_sql_err);
END BEFORE EACH ROW;

AFTER EACH ROW
IS
BEGIN
  
  L_MDMID :=:New.MDMID;
  L_COMPONENT_STYLE_ID :=:NEW.COMPONENT_STYLE_ID;
  L_COMPONENT_DEFAULT := :NEW.COMPONENT_DEFAULT;
  L_COMPONENT_TYPE := :NEW.PEP_COMPONENT_TYPE;
  L_COMPONENT_GROUPING_ID:=:NEW.COMPONENT_GROUPING_ID;

IF (L_COMPONENT_DEFAULT ='true') THEN 
 IF(L_COMPONENT_TYPE in ('Style','StyleColor', 'SKU')) THEN 
		Updatesqlquery:='UPDATE VENDORPORTAL.ADSE_GROUP_CATALOG GRP SET (GRP.DEF_DEPT_ID,GRP.DEF_PRIMARY_SUPPLIER_ID,GRP.DEF_PRIMARYSUPPLIERVPN)= (SELECT DEPT_ID,PRIMARY_SUPPLIER_ID,PRIMARYSUPPLIERVPN FROM ADSE_ITEM_CATALOG ITEM WHERE ITEM.MDMID ='''||L_COMPONENT_STYLE_ID||''') WHERE GRP.MDMID = '||L_MDMID;
		EXECUTE IMMEDIATE Updatesqlquery;
  ELSE  
		Updatesqlquery:='UPDATE VENDORPORTAL.ADSE_GROUP_CATALOG GRP SET (GRP.DEF_DEPT_ID,GRP.DEF_PRIMARY_SUPPLIER_ID,GRP.DEF_PRIMARYSUPPLIERVPN)= (SELECT DEF_DEPT_ID,DEF_PRIMARY_SUPPLIER_ID,DEF_PRIMARYSUPPLIERVPN FROM ADSE_GROUP_CATALOG GRP1 WHERE GRP1.MDMID ='''||L_COMPONENT_GROUPING_ID||''') WHERE GRP.MDMID = '||L_MDMID;
		EXECUTE IMMEDIATE Updatesqlquery;
	END IF;
 END IF;
 


EXCEPTION
  WHEN OTHERS THEN
    L_sql_code := SQLCODE;
    L_sql_err  := SUBSTR(SQLERRM,1,200);
    DBMS_OUTPUT.PUT_LINE ('Trigger T_ADSE_GRPCHLD_TO_GRP_AIUR AFTER EACH ROW Error = '||L_sql_code || L_sql_err);
	raise_application_error(-20000, 'Fatal error from trigger T_ADSE_GRPCHLD_TO_GRP_AIUR AFTER EACH ROW  '||L_sql_code || L_sql_err);
END AFTER EACH ROW;
  
END;
